#!/usr/bin/env bash
# This script is designed to run once for initial spr setup.
# NOTE we checkout repo and download images on first boot
# could consider doing this on build, then just run pull to verify instead

# root user for now

cd /home/spr/super
export SKIP_VPN=1
git pull
./pull_containers.sh # update latest
./virtual_install.sh | tee /tmp/spr_install.log
#bash -c "$(curl -fsSL https://raw.github.com/spr-networks/super/master/virtual_install.sh)"

# Remove the ssh force logout command
sed -e '/Match User root/d' \
    -e '/.*ForceCommand.*droplet.*/d' \
    -i /etc/ssh/sshd_config

systemctl restart ssh

# now add to start spr on boot
cat > /etc/rc.local <<_EOF
#!/bin/bash

cd /home/spr/super && docker-compose up -d
_EOF
chmod +x /etc/rc.local
